name: Sign Python Script Hello World

on:
  push:
    branches:
      - main

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create ZIP Artifact
        run: zip my_artifact.zip hello_world.py

      - name: Submit Signing Request
        run: |
          curl -H "Authorization: Bearer ${{ secrets.SIGNPATH_API_TOKEN }}" \
               -F "ProjectSlug=${{ secrets.PROJECT_SLUG }}" \
               -F "SigningPolicySlug=${{ secrets.SIGNING_POLICY_SLUG }}" \
               -F "Artifact=@my_artifact.zip" \
               ${{ secrets.SIGNPATH_API_URL }}/SigningRequests
